#!/bin/bash
bitbake package-index
HOST='192.168.x.x'
USER='root'
PASS='root'
TARGETFOLDER='/media/sda1/service/ipk-uclibc'
SOURCEFOLDER='/home/user/yocto/poky/build-uclibc/tmp-uclibc/deploy/ipk'
lftp -f "
open $HOST
user $USER $PASS
lcd $SOURCEFOLDER
mirror --reverse --delete --verbose $SOURCEFOLDER $TARGETFOLDER
bye
"

