#!/bin/bash

# Install lftp on your host system, copy this file to /usr/bin on your host (chmod755) 
# and create /media/sda1/.ipkg directory on your coolstream stb.
#
# Adjust HOST (coolstream IP adress) and LCD (your ipk deploy directory) variables to your needs 
# and call ´syncfeeds´ to sync content of your ipk deploy directory with your coolstream stb.
# Don´t forget to ´bitbake package-index´ first.

HOST="192.168.x.x"
USER="root"
PASS=""
FTPURL="ftp://$USER:$PASS@$HOST"
LCD="/home/user/yocto/poky/build-hd2/tmp/deploy/ipk"
RCD="/media/sda1/.ipk"
DELETE="--delete"
lftp -c "set ftp:list-options -a;
open '$FTPURL';
lcd $LCD;
cd $RCD;
mirror --reverse \
       $DELETE \
       --verbose \
       --exclude-glob a-dir-to-exclude/ \
       --exclude-glob a-file-to-exclude \
       --exclude-glob a-file-group-to-exclude* \
       --exclude-glob other-files-to-exclude"

