#!/bin/sh

create_node() {
	device=$1

	rm -f /dev/${device}
	major=`awk "\\$2==\"$device\" {print \\$1}" /proc/devices`

	if [ ${major} ]; then
		echo "  creating device node for $1"
		#echo "    DEBUG: mknod /dev/${device} c $major 0"
		mknod /dev/${device} c $major 0
	fi
}

create_node_dir() {
	device=$1

	rm -rf /dev/${device}
	mkdir -p /dev/${device}

	major=`awk "\\$2==\"$device\" {print \\$1}" /proc/devices`

	if [ ${major} ]; then
		echo "  creating device node for directory $1"
		#echo "    DEBUG: mknod /dev/${device}/0 c $major 0"
		mknod /dev/${device}/0 c $major 0
	fi
}

case $1 in
start)
	create_node     "KAL"
	create_node     "notifyq"
	create_node     "platform"
	create_node     "content"
	create_node     "standby"
	create_node     "video"
	create_node     "audio"
	create_node     "pvr"
	create_node     "ci"
	create_node     "cs_control"
	create_node     "cs_display"
	create_node     "cs_ir"
	create_node     "FrontEnd"
	create_node     "ipfe"
	create_node     "pvrsrvkm"
	create_node     "vss_bc"
	create_node_dir	"input"
	create_node_dir	"fb"

	ln -sf /dev/cs_display /dev/display
	ln -sf /dev/cs_ir /dev/input/nevis_ir
	ln -sf /dev/cs_ir /dev/input/event0
	ln -sf /dev/fb0 /dev/fb/0
	;;
esac
